[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "rare boring make loop toward throw point slow extra churn virtual mystery news fan slot people twin immense clock tuna betray iron general minimum"
